### ISSUE TITLE
File check

### ISSUE THREAD

**Issue by devillD** [1Danish-00/CompressorBot#16]
Please include file type and file size checker
So that, the user users can't compress a file until it's a video and within the file size limit

**Comment by 1Danish-00** [comment]
its already there.

**Comment by 1Danish-00** [comment]
> Please include file type and file size checker
> So that, the user users can't compress a file until it's a video and within the file size limit

Its already There

**Comment by D34DPUL** [comment]
> > Please include file type and file size checker
> > So that, the user users can't compress a file until it's a video and within the file size limit
> 
> Its already There

Where can i set that value??

Also its giving error when trying links

helper: 'NoneType' object has no attribute 'split'

**Comment by D34DPUL** [comment]
already on latest commit but links doesn't seem to work
