### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Attacker336699** [1Danish-00/CompressorBot#33]
ERRNO NO SUCH FILE DIRECTORY ITS COMING

**Comment by TanujairamV** [comment]
For me also

**Comment by ghost** [comment]
Same here

**Comment by Sh1vam** [comment]
May be he has high work load in clg in studies so maintainance of bot is not done

**Comment by 1Danish-00** [comment]
> ERRNO NO SUCH FILE DIRECTORY ITS COMING

Explain a bit more please.

**Comment by TanujairamV** [comment]
> > ERRNO NO SUCH FILE DIRECTORY ITS COMING
> 
> Explain a bit more please.

When I deployed in heroku it shows 
Error no such file in directory 

You can deploy and check 
And fix this issue


And heroku also going to winde up their free service 

Try to make the repo support for a free alternative vps

**Comment by 1Danish-00** [comment]
> > > ERRNO NO SUCH FILE DIRECTORY ITS COMING
> > 
> > 
> > Explain a bit more please.
> 
> When I deployed in heroku it shows Error no such file in directory
> 
> You can deploy and check And fix this issue
> 
> And heroku also going to winde up their free service
> 
> Try to make the repo support for a free alternative vps

okay sure
