### ISSUE TITLE
Unable to request multiple file compression in 1request

### ISSUE THREAD

**Issue by Sibasish** [1Danish-00/CompressorBot#38]
I know the bot has limitations of taking one file request at a time. But the bot should at least fetch multiple files one by one after each gets completed. Look into it if that functionality can be added. Also, do the functionality of entering data stream in kBps for individual or bulk files

**Comment by Sh1vam** [comment]
> I know the bot has limitations of taking one file request at a time. But the bot should at least fetch multiple files one by one after each gets completed. Look into it if that functionality can be added. Also, do the functionality of entering data stream in kBps for individual or bulk files 

Y dont u try yourself may be developer busy in studies

**Comment by Sibasish** [comment]
I don't know how to look into the code. I just gave you feedback for improvement. It's up to you if you take it or not. I have no idea how to implement the same. Otherwise, I would have done it on my own. If you could guide me regarding this, I would definitely like to try

**Comment by 1Danish-00** [comment]
> I know the bot has limitations of taking one file request at a time. But the bot should at least fetch multiple files one by one after each gets completed. Look into it if that functionality can be added. Also, do the functionality of entering data stream in kBps for individual or bulk files

https://github.com/1danish-00/compressorqueue
https://github.com/1danish-00/compressorqueue
