### ISSUE TITLE
please add compress from url video

### ISSUE THREAD

**Issue by alamia442** [1Danish-00/CompressorBot#5]
hi can you add feature to allow bot compress from video url?
because download speed from telegram video very slow only 500-900kbps

✦ Downloading

[𒊹︎︎︎𒊹︎︎︎𒊹︎︎︎𒊹︎︎︎𒊹︎︎︎𒊹︎︎︎𒊹︎︎︎●●●●●●●●●●●●●] 35.11%

238.0 MB of 677.81 MB

✦ Speed: 312.36 KB/s

✦ ETA: 24m, 2s

**Comment by 1Danish-00** [comment]
Did some fixes and increased some speed update ur bot and try 😅
